import type { User, Question, Space, Vendor } from "@shared/schema";

export const mockUsers: User[] = [
  {
    id: "1",
    username: "jennifer.smith",
    name: "Jennifer Smith",
    title: "Brand at Modern Media",
    company: "Modern Media",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    bio: "Marketing professional with 10+ years experience",
    posts: 15,
    views: 2500,
    thanks: 45,
    insightful: 32,
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "2",
    username: "eckart.walther",
    name: "Eckart Walther",
    title: "CMO at Modern Media",
    company: "Modern Media",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    bio: "Chief Marketing Officer specializing in B2B growth",
    posts: 43,
    views: 4300,
    thanks: 105,
    insightful: 342,
    createdAt: new Date("2022-03-10"),
  },
  {
    id: "3",
    username: "hilary.jones",
    name: "Hilary Jones",
    title: "Performance Marketing Lead at Modern Media",
    company: "Modern Media",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    bio: "Performance marketing specialist",
    posts: 28,
    views: 1800,
    thanks: 67,
    insightful: 89,
    createdAt: new Date("2022-08-22"),
  },
  {
    id: "4",
    username: "john.smith",
    name: "John Smith",
    title: "CMO at Modern Media",
    company: "Modern Media",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.0.3&auto=format&fit=crop&w=100&h=100",
    bio: "Marketing leader focused on digital transformation",
    posts: 127,
    views: 8900,
    thanks: 234,
    insightful: 456,
    createdAt: new Date("2021-11-05"),
  },
];

export const mockQuestions: Question[] = [
  {
    id: "1",
    title: "Do you have any experience with deploying @Hubspot?",
    content: "We are a series A B2B startup with a custom solution today. We are using @Mixpanel and working with @Division of Labor to rebuild our pages. @Jennifer Smith, Would love your thoughts as well.",
    authorId: "1",
    category: "Retouch",
    tags: ["content-marketing", "branding"],
    imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    createdAt: new Date("2023-11-20"),
  },
  {
    id: "2",
    title: "Best practices for B2B lead generation?",
    content: "We have used @Hubspot extensively for our business, and are generally very happy with them. We started with a custom solution, and it took us a month to switch, the results have been dramatic, and feel free. See more",
    authorId: "3",
    category: "Performance Marketing",
    tags: ["lead-generation", "b2b"],
    imageUrl: undefined,
    createdAt: new Date("2023-11-23"),
  },
  {
    id: "3",
    title: "Do you have any experience with deploying @Hubspot?",
    content: "We are a series A B2B startup with a custom solution today. We are using @Mixpanel and working with... See more",
    authorId: "2",
    category: "Retouch",
    tags: ["content-marketing", "branding"],
    imageUrl: undefined,
    createdAt: new Date("2023-11-20"),
  },
];

export const mockSpaces: Space[] = [
  {
    id: "1",
    name: "Advertising",
    hashtag: "#advertising",
    count: 22,
    isActive: true,
  },
  {
    id: "2",
    name: "Performance Marketing",
    hashtag: "#performance-m...",
    count: 0,
    isActive: false,
  },
  {
    id: "3",
    name: "Social Media Marketing",
    hashtag: "#social-media-m...",
    count: 0,
    isActive: false,
  },
  {
    id: "4",
    name: "Public Relations",
    hashtag: "#public-relations",
    count: 3,
    isActive: true,
  },
  {
    id: "5",
    name: "Design",
    hashtag: "#design",
    count: 0,
    isActive: false,
  },
  {
    id: "6",
    name: "Account Based Marketing",
    hashtag: "#account-based...",
    count: 0,
    isActive: false,
  },
  {
    id: "7",
    name: "Content Marketing",
    hashtag: "#content-marke...",
    count: 17,
    isActive: true,
  },
  {
    id: "8",
    name: "Conversion Rate Optimization",
    hashtag: "#conversion-rat...",
    count: 0,
    isActive: false,
  },
  {
    id: "9",
    name: "Demand Generation",
    hashtag: "#demand-gener...",
    count: 0,
    isActive: false,
  },
];

export const mockVendors: Vendor[] = [
  {
    id: "1",
    name: "Mixpanel",
    location: "San Francisco, CA",
    initials: "MP",
    color: "bg-blue-100 text-blue-600",
  },
  {
    id: "2",
    name: "Hubspot",
    location: "Boston, MA",
    initials: "H",
    color: "bg-orange-100 text-orange-600",
  },
  {
    id: "3",
    name: "Division of Labor",
    location: "San Francisco, CA",
    initials: "DL",
    color: "bg-red-100 text-red-600",
  },
];
